### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by testbot-github**
added link

### CODE REVIEW

**Comment by testbot-github** [comment]
added a new section with a bunch of rickrolls 😄

**Comment by testbot-github** [comment]
added youtube rickrolls 
add more from here if u want - [https://www.youtube.com/watch?v=ikFZLI4HLpQ&list=PLKIxB9vhdS_3x0A5za3mmu1wdoolgRQ65&index=11](https://www.youtube.com/watch?v=ikFZLI4HLpQ&list=PLKIxB9vhdS_3x0A5za3mmu1wdoolgRQ65&index=11)

**Comment by testbot-github** [comment]
@aboutDavid

**Comment by aboutDavid** [comment]
thanks!

**Pull request merged**
