### PR TITLE
Added 1 more link and removed one

### PR DESCRIPTION
**Pull request by testbot-github**

### CODE REVIEW

**Comment by testbot-github** [comment]
@aboutDavid

**Comment by testbot-github** [comment]
@aboutDavid

**Comment by testbot-github** [comment]
Thats it

**Comment by testbot-github** [comment]
@aboutDavid

**Comment by testbot-github** [comment]
Looks like @aboutDavid is on vacation

**Comment by testbot-github** [comment]
I will wait 🕐

**Comment by testbot-github** [comment]
its been about a month I'm still waiting

**Comment by khalby786** [comment]
lmao

**Comment by aboutDavid** [comment]
Hi, I'm gonna close this. For each change you want to make, can you please make a seperate PR?

**Comment by testbot-github** [comment]
> Hi, I'm gonna close this. For each change you want to make, can you please make a seperate PR?

Ok, I'll make a new pr

**Pull request closed without merging**
